In [ ]:
# Phase 2 – SQL Integration

In [1]:
# Install required libraries (only once)
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.3.0)
Requirement already satisfied: sqlalchemy in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.2.0)
Requirement already satisfied: numpy>=1.23.2 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (4.14.0)
Requirement already satisfied: six>=1.5 in C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Ignoring invalid distribution ~ip (C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\91982\AppData\Local\Programs\Python\Python311\Lib\site-packages)

In [2]:
# Import libraries in Python
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# Create MySQL connection
engine = create_engine("mysql+pymysql://root:rohit20060705@127.0.0.1/HousePriceDB")

In [4]:
# Test Connection
pd.read_sql("SHOW TABLES", engine)

  Tables_in_housepricedb
0                housing

In [5]:
# 5. Load Table from MySQL
# Table columns now: longitude, latitude, housing_median_age, total_rooms,
# total_bedrooms, population, households, median_income, median_house_value, ocean_proximity
df = pd.read_sql("SELECT * FROM housing", engine)
# Display First Rows
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [6]:
# Check shape
print(df.shape)

(20433, 10)

In [7]:
# Check data types
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20433 entries, 0 to 20432
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB
None

In [8]:
# Check missing values
# NOTE: 'total_bedrooms' is expected to have some missing values in this dataset
print(df.isnull().sum())

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [9]:
# Check duplicate rows
print(df.duplicated().sum())

0